// @generated by protoc-gen-es v2.2.2 with parameter "target=ts,json_types=true"
// @generated from file api/v1/bank.proto (package api.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import type { Bank, BankBranch, BankBranchJson, BankJson } from "./common_pb";
import { file_api_v1_common } from "./common_pb";
import { file_buf_validate_validate } from "../../buf/validate/validate_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file api/v1/bank.proto.
 */
export const file_api_v1_bank: GenFile = /*@__PURE__*/
  fileDesc("ChFhcGkvdjEvYmFuay5wcm90bxIGYXBpLnYxIjAKDkdldEJhbmtSZXF1ZXN0Eh4KCWJhbmtfY29kZRgBIAEoCUILukgIyAEBcgOYAQQiNQoPR2V0QmFua1Jlc3BvbnNlEiIKBGJhbmsYASABKAsyDC5hcGkudjEuQmFua0IGukgDyAEBIhYKFEdldE1ham9yQmFua3NSZXF1ZXN0IoUBChVHZXRNYWpvckJhbmtzUmVzcG9uc2USJAoGbWl6dWhvGAEgASgLMgwuYXBpLnYxLkJhbmtCBrpIA8gBARIiCgRtdWZnGAIgASgLMgwuYXBpLnYxLkJhbmtCBrpIA8gBARIiCgRzbWJjGAMgASgLMgwuYXBpLnYxLkJhbmtCBrpIA8gBASIxChJTZWFyY2hCYW5rc1JlcXVlc3QSGwoFcXVlcnkYASABKAlCDLpICcgBAXIEEAEYMiIyChNTZWFyY2hCYW5rc1Jlc3BvbnNlEhsKBWJhbmtzGAEgAygLMgwuYXBpLnYxLkJhbmsiVAoQR2V0QnJhbmNoUmVxdWVzdBIeCgliYW5rX2NvZGUYASABKAlCC7pICMgBAXIDmAEEEiAKC2JyYW5jaF9jb2RlGAIgASgJQgu6SAjIAQFyA5gBAyI/ChFHZXRCcmFuY2hSZXNwb25zZRIqCgZicmFuY2gYASABKAsyEi5hcGkudjEuQmFua0JyYW5jaEIGukgDyAEBIjQKEkdldEJyYW5jaGVzUmVxdWVzdBIeCgliYW5rX2NvZGUYASABKAlCC7pICMgBAXIDmAEEIjsKE0dldEJyYW5jaGVzUmVzcG9uc2USJAoIYnJhbmNoZXMYASADKAsyEi5hcGkudjEuQmFua0JyYW5jaCJUChVTZWFyY2hCcmFuY2hlc1JlcXVlc3QSHgoJYmFua19jb2RlGAEgASgJQgu6SAjIAQFyA5gBBBIbCgVxdWVyeRgCIAEoCUIMukgJyAEBcgQQARgyIj4KFlNlYXJjaEJyYW5jaGVzUmVzcG9uc2USJAoIYnJhbmNoZXMYASADKAsyEi5hcGkudjEuQmFua0JyYW5jaDLGAwoLQmFua1NlcnZpY2USPAoHR2V0QmFuaxIWLmFwaS52MS5HZXRCYW5rUmVxdWVzdBoXLmFwaS52MS5HZXRCYW5rUmVzcG9uc2UiABJOCg1HZXRNYWpvckJhbmtzEhwuYXBpLnYxLkdldE1ham9yQmFua3NSZXF1ZXN0Gh0uYXBpLnYxLkdldE1ham9yQmFua3NSZXNwb25zZSIAEkgKC1NlYXJjaEJhbmtzEhouYXBpLnYxLlNlYXJjaEJhbmtzUmVxdWVzdBobLmFwaS52MS5TZWFyY2hCYW5rc1Jlc3BvbnNlIgASQgoJR2V0QnJhbmNoEhguYXBpLnYxLkdldEJyYW5jaFJlcXVlc3QaGS5hcGkudjEuR2V0QnJhbmNoUmVzcG9uc2UiABJICgtHZXRCcmFuY2hlcxIaLmFwaS52MS5HZXRCcmFuY2hlc1JlcXVlc3QaGy5hcGkudjEuR2V0QnJhbmNoZXNSZXNwb25zZSIAElEKDlNlYXJjaEJyYW5jaGVzEh0uYXBpLnYxLlNlYXJjaEJyYW5jaGVzUmVxdWVzdBoeLmFwaS52MS5TZWFyY2hCcmFuY2hlc1Jlc3BvbnNlIgBCbQoKY29tLmFwaS52MUIJQmFua1Byb3RvUAFaG2FwaS9wcm90by9nZW4vYXBpL3YxO2FwaV92MaICA0FYWKoCBkFwaS5WMcoCBkFwaVxWMeICEkFwaVxWMVxHUEJNZXRhZGF0YeoCB0FwaTo6VjFiBnByb3RvMw", [file_api_v1_common, file_buf_validate_validate]);

/**
 * @generated from message api.v1.GetBankRequest
 */
export type GetBankRequest = Message<"api.v1.GetBankRequest"> & {
  /**
   * @generated from field: string bank_code = 1;
   */
  bankCode: string;
};

/**
 * @generated from message api.v1.GetBankRequest
 */
export type GetBankRequestJson = {
  /**
   * @generated from field: string bank_code = 1;
   */
  bankCode?: string;
};

/**
 * Describes the message api.v1.GetBankRequest.
 * Use `create(GetBankRequestSchema)` to create a new message.
 */
export const GetBankRequestSchema: GenMessage<GetBankRequest, GetBankRequestJson> = /*@__PURE__*/
  messageDesc(file_api_v1_bank, 0);

/**
 * @generated from message api.v1.GetBankResponse
 */
export type GetBankResponse = Message<"api.v1.GetBankResponse"> & {
  /**
   * @generated from field: api.v1.Bank bank = 1;
   */
  bank?: Bank;
};

/**
 * @generated from message api.v1.GetBankResponse
 */
export type GetBankResponseJson = {
  /**
   * @generated from field: api.v1.Bank bank = 1;
   */
  bank?: BankJson;
};

/**
 * Describes the message api.v1.GetBankResponse.
 * Use `create(GetBankResponseSchema)` to create a new message.
 */
export const GetBankResponseSchema: GenMessage<GetBankResponse, GetBankResponseJson> = /*@__PURE__*/
  messageDesc(file_api_v1_bank, 1);

/**
 * @generated from message api.v1.GetMajorBanksRequest
 */
export type GetMajorBanksRequest = Message<"api.v1.GetMajorBanksRequest"> & {
};

/**
 * @generated from message api.v1.GetMajorBanksRequest
 */
export type GetMajorBanksRequestJson = {
};

/**
 * Describes the message api.v1.GetMajorBanksRequest.
 * Use `create(GetMajorBanksRequestSchema)` to create a new message.
 */
export const GetMajorBanksRequestSchema: GenMessage<GetMajorBanksRequest, GetMajorBanksRequestJson> = /*@__PURE__*/
  messageDesc(file_api_v1_bank, 2);

/**
 * @generated from message api.v1.GetMajorBanksResponse
 */
export type GetMajorBanksResponse = Message<"api.v1.GetMajorBanksResponse"> & {
  /**
   * @generated from field: api.v1.Bank mizuho = 1;
   */
  mizuho?: Bank;

  /**
   * @generated from field: api.v1.Bank mufg = 2;
   */
  mufg?: Bank;

  /**
   * @generated from field: api.v1.Bank smbc = 3;
   */
  smbc?: Bank;
};

/**
 * @generated from message api.v1.GetMajorBanksResponse
 */
export type GetMajorBanksResponseJson = {
  /**
   * @generated from field: api.v1.Bank mizuho = 1;
   */
  mizuho?: BankJson;

  /**
   * @generated from field: api.v1.Bank mufg = 2;
   */
  mufg?: BankJson;

  /**
   * @generated from field: api.v1.Bank smbc = 3;
   */
  smbc?: BankJson;
};

/**
 * Describes the message api.v1.GetMajorBanksResponse.
 * Use `create(GetMajorBanksResponseSchema)` to create a new message.
 */
export const GetMajorBanksResponseSchema: GenMessage<GetMajorBanksResponse, GetMajorBanksResponseJson> = /*@__PURE__*/
  messageDesc(file_api_v1_bank, 3);

/**
 * @generated from message api.v1.SearchBanksRequest
 */
export type SearchBanksRequest = Message<"api.v1.SearchBanksRequest"> & {
  /**
   * Arbitrary query keyword to search banks.
   *
   * @generated from field: string query = 1;
   */
  query: string;
};

/**
 * @generated from message api.v1.SearchBanksRequest
 */
export type SearchBanksRequestJson = {
  /**
   * Arbitrary query keyword to search banks.
   *
   * @generated from field: string query = 1;
   */
  query?: string;
};

/**
 * Describes the message api.v1.SearchBanksRequest.
 * Use `create(SearchBanksRequestSchema)` to create a new message.
 */
export const SearchBanksRequestSchema: GenMessage<SearchBanksRequest, SearchBanksRequestJson> = /*@__PURE__*/
  messageDesc(file_api_v1_bank, 4);

/**
 * @generated from message api.v1.SearchBanksResponse
 */
export type SearchBanksResponse = Message<"api.v1.SearchBanksResponse"> & {
  /**
   * @generated from field: repeated api.v1.Bank banks = 1;
   */
  banks: Bank[];
};

/**
 * @generated from message api.v1.SearchBanksResponse
 */
export type SearchBanksResponseJson = {
  /**
   * @generated from field: repeated api.v1.Bank banks = 1;
   */
  banks?: BankJson[];
};

/**
 * Describes the message api.v1.SearchBanksResponse.
 * Use `create(SearchBanksResponseSchema)` to create a new message.
 */
export const SearchBanksResponseSchema: GenMessage<SearchBanksResponse, SearchBanksResponseJson> = /*@__PURE__*/
  messageDesc(file_api_v1_bank, 5);

/**
 * @generated from message api.v1.GetBranchRequest
 */
export type GetBranchRequest = Message<"api.v1.GetBranchRequest"> & {
  /**
   * @generated from field: string bank_code = 1;
   */
  bankCode: string;

  /**
   * @generated from field: string branch_code = 2;
   */
  branchCode: string;
};

/**
 * @generated from message api.v1.GetBranchRequest
 */
export type GetBranchRequestJson = {
  /**
   * @generated from field: string bank_code = 1;
   */
  bankCode?: string;

  /**
   * @generated from field: string branch_code = 2;
   */
  branchCode?: string;
};

/**
 * Describes the message api.v1.GetBranchRequest.
 * Use `create(GetBranchRequestSchema)` to create a new message.
 */
export const GetBranchRequestSchema: GenMessage<GetBranchRequest, GetBranchRequestJson> = /*@__PURE__*/
  messageDesc(file_api_v1_bank, 6);

/**
 * @generated from message api.v1.GetBranchResponse
 */
export type GetBranchResponse = Message<"api.v1.GetBranchResponse"> & {
  /**
   * @generated from field: api.v1.BankBranch branch = 1;
   */
  branch?: BankBranch;
};

/**
 * @generated from message api.v1.GetBranchResponse
 */
export type GetBranchResponseJson = {
  /**
   * @generated from field: api.v1.BankBranch branch = 1;
   */
  branch?: BankBranchJson;
};

/**
 * Describes the message api.v1.GetBranchResponse.
 * Use `create(GetBranchResponseSchema)` to create a new message.
 */
export const GetBranchResponseSchema: GenMessage<GetBranchResponse, GetBranchResponseJson> = /*@__PURE__*/
  messageDesc(file_api_v1_bank, 7);

/**
 * @generated from message api.v1.GetBranchesRequest
 */
export type GetBranchesRequest = Message<"api.v1.GetBranchesRequest"> & {
  /**
   * @generated from field: string bank_code = 1;
   */
  bankCode: string;
};

/**
 * @generated from message api.v1.GetBranchesRequest
 */
export type GetBranchesRequestJson = {
  /**
   * @generated from field: string bank_code = 1;
   */
  bankCode?: string;
};

/**
 * Describes the message api.v1.GetBranchesRequest.
 * Use `create(GetBranchesRequestSchema)` to create a new message.
 */
export const GetBranchesRequestSchema: GenMessage<GetBranchesRequest, GetBranchesRequestJson> = /*@__PURE__*/
  messageDesc(file_api_v1_bank, 8);

/**
 * @generated from message api.v1.GetBranchesResponse
 */
export type GetBranchesResponse = Message<"api.v1.GetBranchesResponse"> & {
  /**
   * @generated from field: repeated api.v1.BankBranch branches = 1;
   */
  branches: BankBranch[];
};

/**
 * @generated from message api.v1.GetBranchesResponse
 */
export type GetBranchesResponseJson = {
  /**
   * @generated from field: repeated api.v1.BankBranch branches = 1;
   */
  branches?: BankBranchJson[];
};

/**
 * Describes the message api.v1.GetBranchesResponse.
 * Use `create(GetBranchesResponseSchema)` to create a new message.
 */
export const GetBranchesResponseSchema: GenMessage<GetBranchesResponse, GetBranchesResponseJson> = /*@__PURE__*/
  messageDesc(file_api_v1_bank, 9);

/**
 * @generated from message api.v1.SearchBranchesRequest
 */
export type SearchBranchesRequest = Message<"api.v1.SearchBranchesRequest"> & {
  /**
   * @generated from field: string bank_code = 1;
   */
  bankCode: string;

  /**
   * @generated from field: string query = 2;
   */
  query: string;
};

/**
 * @generated from message api.v1.SearchBranchesRequest
 */
export type SearchBranchesRequestJson = {
  /**
   * @generated from field: string bank_code = 1;
   */
  bankCode?: string;

  /**
   * @generated from field: string query = 2;
   */
  query?: string;
};

/**
 * Describes the message api.v1.SearchBranchesRequest.
 * Use `create(SearchBranchesRequestSchema)` to create a new message.
 */
export const SearchBranchesRequestSchema: GenMessage<SearchBranchesRequest, SearchBranchesRequestJson> = /*@__PURE__*/
  messageDesc(file_api_v1_bank, 10);

/**
 * @generated from message api.v1.SearchBranchesResponse
 */
export type SearchBranchesResponse = Message<"api.v1.SearchBranchesResponse"> & {
  /**
   * @generated from field: repeated api.v1.BankBranch branches = 1;
   */
  branches: BankBranch[];
};

/**
 * @generated from message api.v1.SearchBranchesResponse
 */
export type SearchBranchesResponseJson = {
  /**
   * @generated from field: repeated api.v1.BankBranch branches = 1;
   */
  branches?: BankBranchJson[];
};

/**
 * Describes the message api.v1.SearchBranchesResponse.
 * Use `create(SearchBranchesResponseSchema)` to create a new message.
 */
export const SearchBranchesResponseSchema: GenMessage<SearchBranchesResponse, SearchBranchesResponseJson> = /*@__PURE__*/
  messageDesc(file_api_v1_bank, 11);

/**
 * @generated from service api.v1.BankService
 */
export const BankService: GenService<{
  /**
   * GetBank returns a bank by the bank code.
   *
   * @generated from rpc api.v1.BankService.GetBank
   */
  getBank: {
    methodKind: "unary";
    input: typeof GetBankRequestSchema;
    output: typeof GetBankResponseSchema;
  },
  /**
   * GetMajorBanks returns a list of major banks to render Mizuho, SMBC, and MUFG in Core UI.
   *
   * @generated from rpc api.v1.BankService.GetMajorBanks
   */
  getMajorBanks: {
    methodKind: "unary";
    input: typeof GetMajorBanksRequestSchema;
    output: typeof GetMajorBanksResponseSchema;
  },
  /**
   * SearchBanks returns a list of banks that match the query.
   *
   * @generated from rpc api.v1.BankService.SearchBanks
   */
  searchBanks: {
    methodKind: "unary";
    input: typeof SearchBanksRequestSchema;
    output: typeof SearchBanksResponseSchema;
  },
  /**
   * GetBranch returns a branch by the bank code and branch code.
   *
   * @generated from rpc api.v1.BankService.GetBranch
   */
  getBranch: {
    methodKind: "unary";
    input: typeof GetBranchRequestSchema;
    output: typeof GetBranchResponseSchema;
  },
  /**
   * GetBranches returns a list of branches by the bank code.
   *
   * @generated from rpc api.v1.BankService.GetBranches
   */
  getBranches: {
    methodKind: "unary";
    input: typeof GetBranchesRequestSchema;
    output: typeof GetBranchesResponseSchema;
  },
  /**
   * SearchBranches returns a list of branches that match the query.
   *
   * @generated from rpc api.v1.BankService.SearchBranches
   */
  searchBranches: {
    methodKind: "unary";
    input: typeof SearchBranchesRequestSchema;
    output: typeof SearchBranchesResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_api_v1_bank, 0);

