// @generated by protoc-gen-es v2.2.2 with parameter "target=ts,json_types=true"
// @generated from file api/v1/healthcheck.proto (package api.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import { file_google_api_annotations } from "../../google/api/annotations_pb";
import { file_protoc_gen_openapiv2_options_annotations } from "../../protoc-gen-openapiv2/options/annotations_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file api/v1/healthcheck.proto.
 */
export const file_api_v1_healthcheck: GenFile = /*@__PURE__*/
  fileDesc("ChhhcGkvdjEvaGVhbHRoY2hlY2sucHJvdG8SBmFwaS52MSINCgtQaW5nUmVxdWVzdCIaCgxQaW5nUmVzcG9uc2USCgoCb2sYASABKAgywwEKEkhlYWx0aGNoZWNrU2VydmljZRKsAQoEUGluZxITLmFwaS52MS5QaW5nUmVxdWVzdBoULmFwaS52MS5QaW5nUmVzcG9uc2UieZJBXwoLaGVhbHRoY2hlY2sSJFBpbmcgSmFtbSBzZXJ2ZXIgdG8gY2hlY2sgY29ubmVjdGlvbhokUGluZyBKYW1tIHNlcnZlciB0byBjaGVjayBjb25uZWN0aW9uKgRwaW5ngtPkkwIREg8vdjEvaGVhbHRoY2hlY2tCdAoKY29tLmFwaS52MUIQSGVhbHRoY2hlY2tQcm90b1ABWhthcGkvcHJvdG8vZ2VuL2FwaS92MTthcGlfdjGiAgNBWFiqAgZBcGkuVjHKAgZBcGlcVjHiAhJBcGlcVjFcR1BCTWV0YWRhdGHqAgdBcGk6OlYxYgZwcm90bzM", [file_google_api_annotations, file_protoc_gen_openapiv2_options_annotations]);

/**
 * @generated from message api.v1.PingRequest
 */
export type PingRequest = Message<"api.v1.PingRequest"> & {
};

/**
 * @generated from message api.v1.PingRequest
 */
export type PingRequestJson = {
};

/**
 * Describes the message api.v1.PingRequest.
 * Use `create(PingRequestSchema)` to create a new message.
 */
export const PingRequestSchema: GenMessage<PingRequest, PingRequestJson> = /*@__PURE__*/
  messageDesc(file_api_v1_healthcheck, 0);

/**
 * @generated from message api.v1.PingResponse
 */
export type PingResponse = Message<"api.v1.PingResponse"> & {
  /**
   * @generated from field: bool ok = 1;
   */
  ok: boolean;
};

/**
 * @generated from message api.v1.PingResponse
 */
export type PingResponseJson = {
  /**
   * @generated from field: bool ok = 1;
   */
  ok?: boolean;
};

/**
 * Describes the message api.v1.PingResponse.
 * Use `create(PingResponseSchema)` to create a new message.
 */
export const PingResponseSchema: GenMessage<PingResponse, PingResponseJson> = /*@__PURE__*/
  messageDesc(file_api_v1_healthcheck, 1);

/**
 * @generated from service api.v1.HealthcheckService
 */
export const HealthcheckService: GenService<{
  /**
   * Ping Jamm server to check connection.
   *
   * @generated from rpc api.v1.HealthcheckService.Ping
   */
  ping: {
    methodKind: "unary";
    input: typeof PingRequestSchema;
    output: typeof PingResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_api_v1_healthcheck, 0);

